### ISSUE TITLE
Improve method of failing a command

### ISSUE THREAD

**Issue by a2** [nsomar/Guaka#71]
Currently, [`fail(statusCode:errorMessage:)`](https://github.com/oarrabi/Guaka/blob/ae3e911aa7bd596495c3aaf6df65e4297e7e8412/Sources/Guaka/Command/Command.swift#L380-L388) is defined on [`Command`](https://github.com/oarrabi/Guaka/blob/ae3e911aa7bd596495c3aaf6df65e4297e7e8412/Sources/Guaka/Command/Command.swift), but the default [`run`](https://github.com/oarrabi/Guaka/blob/ae3e911aa7bd596495c3aaf6df65e4297e7e8412/Sources/Guaka/Command/CommandTypes.swift#L36-L38) signature does not pass the command in, so the only way to actually fail a command is to do something like this:

```swift
let command = Command(usage: "foo", run: nil)
command.run = { flags, args in
    command.fail(statusCode: 1, errorMessage: "bar")
}
```

Ideally it would be nice to do something like:

```swift
let command = Command(usage: "foo") { cmd, flags, args in
    cmd.fail(statusCode: 1, errorMessage: "bar")
}
```

or even to allow the `run` handler to `throw`, in which case Guaka would print some error (or even use `description` if the error is `CustomStringConvertible`?)

```swift
enum FooError: Error, CustomStringConvertible {
    case bar

    var description: String {
        switch self {
        case .bar:
            return "bar"
        }
    }
}

let command = Command(usage: "foo") { flags, args in
    throw FooError.bar
}
```

**Comment by oarrabi** [comment]
Hey @a2 and thanks for the proposal :)

I tried to experiment with bot the approaches. I am a bit more inclined toward the first approach. As ti will be less intrusive to the command run types.

At the moment the run blocks have two types:

```
public typealias Run = (Flags, [String]) -> ()
public typealias ConditionalRun = (Flags, [String]) -> (Bool)
```

If we wanted to go with the second approach, that means we have to make the block throws. 
While this is not a big deal with `Run`, it will look kinda strange with the `ConditionalRun`.

Since with `ConditionalRun` the developer can already choose to return false to stop the running of consecutive calls, it would be weird to also make it throw.

We could however unify both `Run` and `ConditionalRun` so both of them throw and have them throw a `stopExecution` exception when the developer opt to stop the execution, and throw a different error if he wants to exit the command. But it might then feel that we are using exception to control the flow, which is something that I would like to avoid.

It would be helpful to experiment with both of them and see how they look before proceeding with either. 

(cc @goyox86 )

**Comment by a2** [comment]
In the meantime, I've been working around this issue [like so](https://gist.github.com/a2/71c40264f58a3ffa635f6a5dffb9a4b2).

**Comment by Ponyboy47** [comment]
Can this be closed with the addition of the global fail function added by #91?

**Comment by a2** [comment]
@Ponyboy47 Looks good to me :)
