### ISSUE TITLE
Async code

### ISSUE THREAD

**Issue by johandk89** [nsomar/Guaka#74]
Is there a way to run async code?
I want to make a network request but the app exits before the network request returns

**Comment by oarrabi** [comment]
Hello @johandk89,

I think the only way is to convert your code to async. You can do that by adding a lock (or a semaphore) and wait until the network call returns.

If you are using GCD then you can use a DispatchWorkItem  and call `wait` on it. https://developer.apple.com/reference/dispatch/dispatchworkitem

```
let myQueue = DispatchQueue(label: "samplequeue")
let workItem = DispatchWorkItem {
    do your async work here
}
myQueue.async(execute: workItem)
workItem.wait()
```

You can dispatch both your network request and the work item on the queue (since its serial) and then call wait on the workitem. Since the workitem has been added second it will cause our application to wait until the network request was done.
